### ISSUE TITLE
HGServer crash

### ISSUE THREAD

**Issue by pawelsawicz** [Helbreath/task-board#14]
So yesterday I left server for a whole night nothing crashed. Today, when few people entered in HG has, started crashing.

Investigate why by running in debug mode, see when it crash.

At the beginning, I thought that it's causing some mismatch between `LoginServerConsole` and `HGSever` but I even with `LoginServer` is crash

**Comment by 4LifeX** [comment]
pawel, this is gavin, where r the files? let me try on debug mode and see where it is going wrong. is it the helbreath windows?
