### ISSUE TITLE
Move existing code to console app

### ISSUE THREAD

**Issue by pawelsawicz** [Helbreath/task-board#4]
Check if it's possible to move existing code into console application

- [x] LoginServer
- [x] MapServer

When moved try to establish connection

**Comment by pawelsawicz** [comment]
Checked and there is no extra dependency in existing code except `HWND` (which can be fake).

**Comment by helbreath2016** [comment]
windows event message we can not go to console app. must stay windows.

**Comment by pawelsawicz** [comment]
@helbreath2016 I found that it's still [possible](http://www.winsocketdotnetworkprogramming.com/winsock2programming/winsock2advancediomethod5b.html)

**Comment by helbreath2016** [comment]
we need to talk on skype.
